sudo: required
language: cpp

matrix:
  include:
    - env: BUILD_TYPE=Debug
      compiler: clang
      addons:
        apt:
          packages:
            - bison

    - env: BUILD_TYPE=Release
      compiler: clang

    - env: BUILD_TYPE=Debug
      compiler: gcc
      addons:
        apt:
          packages:
            - bison

    - env: BUILD_TYPE=Release
      compiler: gcc


script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - make
  - ctest
