sudo: required
language: cpp

compiler:
  - clang
  - gcc

before_install:
  - cd 3rd_party/re2c/re2c
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ../../..
  - cd 3rd_party/asn1c
  - test -f configure || autoreconf -iv
  - ./configure
  - sudo make install
  - cd ../..

addons:
  apt:
    packages:
      - bison

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
