sudo: required
language: cpp

before_install:
  - sudo apt update
  - sudo apt install -y bison
  - sudo apt install -y re2c

addons:
  apt:
    packages:
      - bison
      - re2c

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
