platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

image:
  - Visual Studio 2017
  
build_script:
- cmd: >-
    git submodule update --init

    mkdir build
    
    cd build
    
    cmake .. -DCMAKE_BUILD_TYPE="$env:CONFIGURATION"
   
    cmake --build . --config "$env:CONFIGURATION"

test_script:
  - ctest -C "$env:CONFIGURATION"