platform:
  - x64

configuration:
  - Release

image:
  - Visual Studio 2017
  
build_script:
- cmd: >-
    git submodule update --init

    mkdir build
    
    cd build
    
    cmake .. -DCMAKE_BUILD_TYPE=Release -g "NMake Makefiles"
   
    cmake --build . --config Release

test_script:
  - ctest -C Release -j 8
  